### ISSUE TITLE
Error about canvas size!!

### ISSUE THREAD

**Issue by red-sponge** [huchenlei/sd-webui-openpose-editor#29]
I can't load or change the canvas size! How can I solve this problem?"
<img width="957" alt="cavas_size_bug" src="https://github.com/huchenlei/sd-webui-openpose-editor/assets/127950543/a4fdbf23-1adf-4c23-b6f5-01370f15d324">

**Comment by huchenlei** [comment]
So you are unable to input number in the canvas width/height input boxes? 
I need to verify that later when I have the local setup running. Input boxes value are hided because of window size. 

Note:
Change canvas size feature is normally used to fit multiple person from different reference image to the same openpose file. If you just want to zoom in to details of current canvas, use mouse scroll on the canvas should be sufficient.

**Comment by huchenlei** [comment]
Fixed in v0.1.8.
