### ISSUE TITLE
feature request: localization support

### ISSUE THREAD

**Issue by NakiriRuri** [huchenlei/sd-webui-openpose-editor#3]
The text of this extension does not seem to be overwritten by the localization files in webui itself. Any plans to add localization support?

**Comment by huchenlei** [comment]
The extension does not get localization from A1111 because it is a separate web page (not build with gradio). 

The i18n can be achieved using https://vue-i18n.intlify.dev/guide/introduction.html, which I am not so familiar with. I will try to set it up some time later so people can contribute localizations.

**Comment by huchenlei** [comment]
localization support is added in this [commit](https://github.com/huchenlei/sd-webui-openpose-editor/commit/f32bb80ebcb8b5f511546b1cf6482e2e42e2f72d). I only cover the basics. Feel free to PR to add more.
